"""
Marketing Plan PDF Generator

Creates comprehensive, professional marketing plans as PDF exports.

Features:
- Executive summary
- Event overview
- Demographic analysis
- Audience personas
- Marketing strategy
- Ad campaigns (Meta, Google, Email, Social)
- Budget allocation
- Timeline/Gantt chart
- ROI projections
- KPI tracking plan
"""
import io
import re
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional
from fpdf import FPDF


def clean_text_for_pdf(text: str) -> str:
    """Remove emojis and special unicode characters that can't be rendered in PDF."""
    # Remove emojis and other unicode characters outside latin-1 range
    return re.sub(r'[^\x00-\xFF]+', '', text).strip()


class MarketingPlanPDF(FPDF):
    """Enhanced PDF with custom styling for marketing plans."""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        """Custom header for each page."""
        if self.page_no() > 1:  # Skip header on cover page
            self.set_font('Arial', 'I', 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, 'Marketing Plan', 0, 0, 'L')
            self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'R')
            self.ln(15)

    def footer(self):
        """Custom footer."""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by AI Tickets Platform - {datetime.now().strftime("%B %d, %Y")}', 0, 0, 'C')

    def chapter_title(self, title: str, color: tuple = (41, 128, 185)):
        """Add a styled chapter title."""
        self.set_font('Arial', 'B', 16)
        self.set_fill_color(*color)
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, clean_text_for_pdf(title), 0, 1, 'L', True)
        self.ln(4)
        self.set_text_color(0, 0, 0)

    def section_title(self, title: str):
        """Add a section title."""
        self.set_font('Arial', 'B', 12)
        self.set_text_color(52, 73, 94)
        self.cell(0, 10, clean_text_for_pdf(title), 0, 1, 'L')
        self.ln(2)
        self.set_text_color(0, 0, 0)

    def body_text(self, text: str):
        """Add body text."""
        self.set_font('Arial', '', 10)
        self.multi_cell(0, 6, clean_text_for_pdf(text))
        self.ln(2)

    def bullet_point(self, text: str):
        """Add a bullet point."""
        self.set_font('Arial', '', 10)
        x_start = self.get_x()
        self.set_x(x_start + 10)
        # Calculate width: page width - left margin - right margin - indent
        w = self.w - self.l_margin - self.r_margin - 10
        self.multi_cell(w, 6, f'- {clean_text_for_pdf(text)}')
        self.set_x(x_start)

    def metric_box(self, label: str, value: str, x: float, y: float, width: float = 45):
        """Add a styled metric box."""
        self.set_xy(x, y)
        self.set_fill_color(236, 240, 241)
        self.rect(x, y, width, 20, 'F')

        # Label
        self.set_xy(x, y + 3)
        self.set_font('Arial', 'B', 8)
        self.set_text_color(127, 140, 141)
        self.cell(width, 6, clean_text_for_pdf(label), 0, 0, 'C')

        # Value
        self.set_xy(x, y + 10)
        self.set_font('Arial', 'B', 12)
        self.set_text_color(41, 128, 185)
        self.cell(width, 6, clean_text_for_pdf(value), 0, 0, 'C')

        self.set_text_color(0, 0, 0)

    def table_row(self, columns: List[str], widths: List[float], is_header: bool = False):
        """Add a table row."""
        if is_header:
            self.set_font('Arial', 'B', 9)
            self.set_fill_color(41, 128, 185)
            self.set_text_color(255, 255, 255)
        else:
            self.set_font('Arial', '', 9)
            self.set_text_color(0, 0, 0)

        for i, (col, width) in enumerate(zip(columns, widths)):
            self.cell(width, 8, clean_text_for_pdf(col), 1, 0, 'L', is_header)

        self.ln()
        self.set_text_color(0, 0, 0)


def generate_marketing_plan_pdf(
    event: Dict[str, Any],
    venue: Dict[str, Any],
    demographics: Dict[str, Any],
    personas: List[Dict[str, Any]],
    ad_campaigns: List[Dict[str, Any]],
    budget_allocation: Dict[str, Any],
    timeline: List[Dict[str, Any]],
    roi_projections: Dict[str, Any]
) -> bytes:
    """
    Generate a comprehensive marketing plan PDF.

    Args:
        event: Event details (name, date, description, capacity, pricing)
        venue: Venue details (name, address, city, state)
        demographics: Demographic data (age, income, education, interests)
        personas: List of audience personas
        ad_campaigns: List of advertising campaigns (Meta, Google, Email)
        budget_allocation: Budget breakdown by channel
        timeline: Marketing timeline with milestones
        roi_projections: Expected ROI and revenue projections

    Returns:
        PDF file as bytes
    """

    pdf = MarketingPlanPDF()

    # ==================== COVER PAGE ====================
    pdf.add_page()

    # Title
    pdf.set_font('Arial', 'B', 32)
    pdf.set_text_color(41, 128, 185)
    pdf.ln(60)
    pdf.cell(0, 15, 'Marketing Plan', 0, 1, 'C')

    # Event name
    pdf.set_font('Arial', 'B', 24)
    pdf.set_text_color(52, 73, 94)
    pdf.cell(0, 12, event.get('name', 'Event'), 0, 1, 'C')

    # Date
    pdf.set_font('Arial', '', 14)
    pdf.set_text_color(127, 140, 141)
    event_date = event.get('date', datetime.now().strftime('%B %d, %Y'))
    if isinstance(event_date, datetime):
        event_date = event_date.strftime('%B %d, %Y')
    pdf.cell(0, 8, event_date, 0, 1, 'C')

    # Venue
    pdf.cell(0, 8, f"{venue.get('name', 'Venue')}, {venue.get('city', 'City')}", 0, 1, 'C')

    # Generated date
    pdf.ln(80)
    pdf.set_font('Arial', 'I', 10)
    pdf.cell(0, 6, f'Generated: {datetime.now().strftime("%B %d, %Y")}', 0, 1, 'C')

    # ==================== EXECUTIVE SUMMARY ====================
    pdf.add_page()
    pdf.chapter_title('Executive Summary')

    pdf.body_text(
        f"This comprehensive marketing plan outlines the strategy to promote {event['name']}, "
        f"scheduled for {event_date} at {venue['name']} in {venue['city']}, {venue['state']}. "
        f"The event targets {event.get('capacity', 'N/A')} attendees with a multi-channel marketing "
        f"approach designed to maximize reach and conversions."
    )

    pdf.ln(4)

    # Key Metrics
    y_pos = pdf.get_y()
    pdf.metric_box('Total Budget', budget_allocation.get('total_budget_formatted', '$0'), 15, y_pos, 45)
    pdf.metric_box('Target Attendees', str(event.get('capacity', 'N/A')), 65, y_pos, 45)
    pdf.metric_box('Expected Revenue', roi_projections.get('expected_revenue_formatted', '$0'), 115, y_pos, 45)
    pdf.metric_box('Projected ROI', f"{roi_projections.get('roi_multiplier', 0)}x", 165, y_pos, 45)

    pdf.ln(28)

    # ==================== EVENT OVERVIEW ====================
    pdf.chapter_title('Event Overview', (52, 152, 219))

    pdf.section_title('Event Details')
    pdf.bullet_point(f"Name: {event['name']}")
    pdf.bullet_point(f"Date: {event_date}")
    pdf.bullet_point(f"Venue: {venue['name']}, {venue['city']}, {venue['state']}")
    pdf.bullet_point(f"Capacity: {event.get('capacity', 'N/A')} attendees")
    pdf.bullet_point(f"Category: {event.get('category', 'General').title()}")

    if event.get('description'):
        pdf.ln(2)
        pdf.section_title('Description')
        pdf.body_text(event['description'])

    # Ticket tiers
    if event.get('ticket_tiers'):
        pdf.ln(2)
        pdf.section_title('Ticket Tiers')

        pdf.table_row(['Tier', 'Price', 'Quantity', 'Total Revenue'], [60, 40, 40, 50], is_header=True)

        for tier in event['ticket_tiers']:
            tier_name = tier.get('name', 'General')
            price = tier.get('price', 0) / 100  # Convert cents to dollars
            quantity = tier.get('quantity', 0)
            total = price * quantity

            pdf.table_row(
                [tier_name, f'${price:.2f}', str(quantity), f'${total:,.2f}'],
                [60, 40, 40, 50]
            )

    # ==================== DEMOGRAPHIC ANALYSIS ====================
    pdf.add_page()
    pdf.chapter_title('Demographic Analysis', (155, 89, 182))

    pdf.section_title('Venue Location Demographics')

    # Population by radius
    if demographics.get('population'):
        pdf.body_text('Population by Radius:')
        pop_data = demographics['population']
        for radius, count in pop_data.items():
            if isinstance(count, int):
                pdf.bullet_point(f"{radius.replace('_', ' ').title()}: {count:,} people")

    pdf.ln(2)

    # Age distribution
    if demographics.get('age_distribution'):
        pdf.section_title('Age Distribution')
        age_data = demographics['age_distribution']

        pdf.table_row(['Age Range', 'Percentage'], [90, 90], is_header=True)
        for age_range, percentage in sorted(age_data.items()):
            pdf.table_row([age_range, f'{percentage}%'], [90, 90])

    pdf.ln(4)

    # Income distribution
    if demographics.get('income_distribution'):
        pdf.section_title('Income Distribution')
        income_data = demographics['income_distribution']

        pdf.table_row(['Income Range', 'Percentage'], [90, 90], is_header=True)
        for income_range, percentage in sorted(income_data.items()):
            pdf.table_row([income_range, f'{percentage}%'], [90, 90])

    pdf.ln(4)

    # Education
    if demographics.get('education'):
        pdf.section_title('Education Levels')
        edu_data = demographics['education']

        for edu_level, percentage in edu_data.items():
            pdf.bullet_point(f"{edu_level.replace('_', ' ').title()}: {percentage}%")

    pdf.ln(4)

    # Employment sectors
    if demographics.get('employment'):
        pdf.section_title('Top Employment Sectors')
        emp_data = demographics['employment']

        for sector, percentage in sorted(emp_data.items(), key=lambda x: x[1], reverse=True)[:5]:
            pdf.bullet_point(f"{sector.replace('_', ' ').title()}: {percentage}%")

    # ==================== TARGET AUDIENCE PERSONAS ====================
    pdf.add_page()
    pdf.chapter_title('Target Audience Personas', (46, 204, 113))

    for persona in personas:
        pdf.section_title(f"{persona['name']} ({persona['percentage']}% of audience)")

        demo = persona.get('demographics', {})
        if demo:
            pdf.body_text(
                f"Age: {demo.get('age', 'N/A')} | "
                f"Income: {demo.get('income', 'N/A')} | "
                f"Education: {demo.get('education', 'N/A')}"
            )

        psycho = persona.get('psychographics', {})
        if psycho.get('interests'):
            pdf.body_text(f"Interests: {', '.join(psycho['interests'])}")
        if psycho.get('values'):
            pdf.body_text(f"Values: {', '.join(psycho['values'])}")

        media = persona.get('media_consumption', {})
        if media.get('platforms'):
            pdf.body_text(f"Platforms: {', '.join(media['platforms'])}")
        if media.get('peak_hours'):
            pdf.body_text(f"Peak Hours: {', '.join(media['peak_hours'])}")

        marketing = persona.get('marketing_approach', {})
        if marketing.get('messaging'):
            pdf.body_text(f"Messaging: {marketing['messaging']}")
        if marketing.get('channels'):
            pdf.body_text(f"Best Channels: {', '.join(marketing['channels'])}")

        pdf.ln(4)

    # ==================== MARKETING STRATEGY ====================
    pdf.add_page()
    pdf.chapter_title('Marketing Strategy', (230, 126, 34))

    pdf.section_title('Multi-Channel Approach')
    pdf.body_text(
        'This marketing plan employs a comprehensive multi-channel strategy to reach '
        'target audiences where they are most active and engaged.'
    )

    pdf.ln(2)

    # Channel breakdown
    for campaign in ad_campaigns:
        segment = campaign.get('segment', {})
        segment_name = segment.get('name', 'Audience Segment')

        pdf.section_title(f"Strategy for {segment_name}")

        # Meta ads
        if campaign.get('meta_ads'):
            pdf.body_text('Meta Advertising (Facebook/Instagram):')
            for ad in campaign['meta_ads'][:2]:  # Show first 2 ads
                pdf.bullet_point(f"{ad['platform']}: {ad['headline']}")

        # Google ads
        if campaign.get('google_ads'):
            pdf.body_text('Google Advertising (Search/Display):')
            for ad in campaign['google_ads'][:2]:
                pdf.bullet_point(f"{ad['platform']}: {ad['headline']}")

        # Email marketing
        if campaign.get('email_marketing'):
            email = campaign['email_marketing']
            pdf.body_text('Email Marketing:')
            pdf.bullet_point(f"Subject: {email.get('subject', 'N/A')}")

        # Metrics
        pdf.body_text(
            f"Expected Reach: {campaign.get('expected_reach', 'N/A'):,} | "
            f"CTR: {campaign.get('estimated_ctr', 0)}% | "
            f"Budget: {campaign.get('suggested_budget_formatted', '$0')}"
        )

        pdf.ln(3)

    # ==================== BUDGET ALLOCATION ====================
    pdf.add_page()
    pdf.chapter_title('Budget Allocation', (231, 76, 60))

    total_budget = budget_allocation.get('total_budget', 0) / 100

    pdf.body_text(f'Total Marketing Budget: ${total_budget:,.2f}')
    pdf.ln(2)

    if budget_allocation.get('by_channel'):
        pdf.section_title('Budget by Channel')

        pdf.table_row(['Channel', 'Budget', 'Percentage', 'Expected ROI'], [60, 40, 40, 50], is_header=True)

        for channel in budget_allocation['by_channel']:
            pdf.table_row([
                channel['channel'],
                channel['budget_formatted'],
                f"{channel['percentage']}%",
                f"{channel.get('expected_roi', 'N/A')}"
            ], [60, 40, 40, 50])

    pdf.ln(4)

    if budget_allocation.get('by_persona'):
        pdf.section_title('Budget by Audience Segment')

        pdf.table_row(['Segment', 'Budget', 'Percentage'], [80, 50, 60], is_header=True)

        for segment in budget_allocation['by_persona']:
            pdf.table_row([
                segment['segment'],
                segment['budget_formatted'],
                f"{segment['percentage']}%"
            ], [80, 50, 60])

    # ==================== MARKETING TIMELINE ====================
    pdf.add_page()
    pdf.chapter_title('Marketing Timeline', (52, 73, 94))

    pdf.body_text(
        'This timeline outlines key marketing milestones and activities leading up to '
        'the event and post-event engagement.'
    )

    pdf.ln(2)

    if timeline:
        pdf.table_row(['Timeline', 'Activity', 'Channel'], [40, 90, 60], is_header=True)

        for milestone in timeline:
            pdf.table_row([
                milestone.get('timeline', ''),
                milestone.get('activity', ''),
                milestone.get('channel', '')
            ], [40, 90, 60])

    # ==================== ROI PROJECTIONS ====================
    pdf.add_page()
    pdf.chapter_title('ROI Projections', (26, 188, 156))

    pdf.section_title('Expected Performance Metrics')

    y_pos = pdf.get_y()
    pdf.metric_box('Impressions', f"{roi_projections.get('expected_impressions', 0):,}", 15, y_pos, 45)
    pdf.metric_box('Clicks', f"{roi_projections.get('expected_clicks', 0):,}", 65, y_pos, 45)
    pdf.metric_box('Conversions', f"{roi_projections.get('expected_conversions', 0):,}", 115, y_pos, 45)
    pdf.metric_box('Tickets Sold', str(roi_projections.get('expected_tickets', 0)), 165, y_pos, 45)

    pdf.ln(26)

    pdf.section_title('Revenue Projections')

    pdf.bullet_point(f"Marketing Investment: {budget_allocation.get('total_budget_formatted', '$0')}")
    pdf.bullet_point(f"Expected Ticket Revenue: {roi_projections.get('expected_revenue_formatted', '$0')}")
    pdf.bullet_point(f"Net Profit: {roi_projections.get('net_profit_formatted', '$0')}")
    pdf.bullet_point(f"ROI Multiple: {roi_projections.get('roi_multiplier', 0)}x")

    pdf.ln(4)

    pdf.section_title('Success Metrics')
    pdf.body_text('The success of this marketing campaign will be measured by:')

    pdf.bullet_point('Ticket sales conversion rate (target: 4-6%)')
    pdf.bullet_point('Cost per acquisition (CPA) below $15')
    pdf.bullet_point('Email open rate above 25%')
    pdf.bullet_point('Social media engagement rate above 3%')
    pdf.bullet_point('Website traffic increase of 300%+')
    pdf.bullet_point('Overall ROI of 4x or higher')

    # ==================== KPI TRACKING PLAN ====================
    pdf.add_page()
    pdf.chapter_title('KPI Tracking & Analytics', (192, 57, 43))

    pdf.section_title('Key Performance Indicators')

    kpis = [
        ('Impressions', 'Total ad impressions across all channels', 'Daily'),
        ('Click-Through Rate (CTR)', 'Percentage of people who click ads', 'Daily'),
        ('Cost Per Click (CPC)', 'Average cost per ad click', 'Daily'),
        ('Conversion Rate', 'Percentage of clicks that result in sales', 'Daily'),
        ('Cost Per Acquisition (CPA)', 'Average cost to acquire one customer', 'Daily'),
        ('Return on Ad Spend (ROAS)', 'Revenue generated per dollar spent', 'Weekly'),
        ('Email Open Rate', 'Percentage of emails opened', 'Per Campaign'),
        ('Social Engagement', 'Likes, shares, comments on social posts', 'Daily'),
        ('Website Traffic', 'Unique visitors to event page', 'Daily'),
        ('Ticket Sales Velocity', 'Number of tickets sold per day', 'Daily')
    ]

    pdf.table_row(['KPI', 'Definition', 'Frequency'], [55, 90, 45], is_header=True)

    for kpi_name, definition, frequency in kpis:
        pdf.table_row([kpi_name, definition, frequency], [55, 90, 45])

    pdf.ln(4)

    pdf.section_title('Analytics Tools')
    pdf.bullet_point('Google Analytics - Website traffic and conversions')
    pdf.bullet_point('Facebook Ads Manager - Meta campaign performance')
    pdf.bullet_point('Google Ads Dashboard - Search and display performance')
    pdf.bullet_point('Email Platform Analytics - Open rates, CTR, conversions')
    pdf.bullet_point('AI Tickets Platform Dashboard - Real-time ticket sales')

    # ==================== CONCLUSION ====================
    pdf.add_page()
    pdf.chapter_title('Conclusion', (44, 62, 80))

    pdf.body_text(
        f"This marketing plan provides a comprehensive roadmap for promoting {event['name']}. "
        f"By leveraging demographic insights, targeted advertising, and a multi-channel approach, "
        f"we project reaching {roi_projections.get('expected_tickets', 0)} attendees with an ROI "
        f"of {roi_projections.get('roi_multiplier', 0)}x."
    )

    pdf.ln(4)

    pdf.body_text(
        'Success depends on consistent execution, active monitoring of KPIs, and agile optimization '
        'based on performance data. Regular reviews (weekly) will ensure the campaign stays on track '
        'and budgets are allocated to the highest-performing channels.'
    )

    pdf.ln(4)

    pdf.section_title('Next Steps')
    pdf.bullet_point('Set up tracking pixels and analytics (Week 1)')
    pdf.bullet_point('Launch Meta and Google ad campaigns (Week 2)')
    pdf.bullet_point('Begin email marketing sequence (Week 2)')
    pdf.bullet_point('Monitor daily performance and optimize (Ongoing)')
    pdf.bullet_point('Weekly performance reviews with stakeholders')
    pdf.bullet_point('Post-event analysis and learnings documentation')

    # Generate PDF as bytes
    return bytes(pdf.output(dest='S'))


def create_sample_marketing_timeline(event_date: datetime) -> List[Dict[str, Any]]:
    """Generate a sample marketing timeline based on event date."""

    days_until_event = (event_date - datetime.now()).days

    timeline = [
        {'timeline': f'{days_until_event} days out', 'activity': 'Launch marketing campaign, set up tracking', 'channel': 'All Channels'},
        {'timeline': f'{days_until_event - 7} days', 'activity': 'Launch Meta ads (Facebook/Instagram)', 'channel': 'Meta Ads'},
        {'timeline': f'{days_until_event - 7} days', 'activity': 'Launch Google search and display ads', 'channel': 'Google Ads'},
        {'timeline': f'{days_until_event - 5} days', 'activity': 'Send first email campaign to mailing list', 'channel': 'Email'},
        {'timeline': f'{days_until_event - 14} days', 'activity': 'Boost top-performing ads, optimize budget', 'channel': 'All Channels'},
        {'timeline': f'{days_until_event - 14} days', 'activity': 'Launch influencer/affiliate partnerships', 'channel': 'Affiliates'},
        {'timeline': f'{days_until_event - 21} days', 'activity': 'Send "Early Bird" email reminder', 'channel': 'Email'},
        {'timeline': f'{days_until_event - 28} days', 'activity': 'Increase ad spend for final push', 'channel': 'All Channels'},
        {'timeline': f'{days_until_event - 28} days', 'activity': 'Social media countdown posts', 'channel': 'Social Media'},
        {'timeline': f'{days_until_event - 30} days', 'activity': 'Send "Last Chance" email', 'channel': 'Email'},
        {'timeline': 'Event Day', 'activity': 'Live social media coverage, attendee engagement', 'channel': 'Social Media'},
        {'timeline': '1 day after', 'activity': 'Thank you email to attendees', 'channel': 'Email'},
        {'timeline': '3 days after', 'activity': 'Post-event survey and feedback request', 'channel': 'Email'},
        {'timeline': '7 days after', 'activity': 'Share event highlights, photos, testimonials', 'channel': 'Social Media'},
    ]

    return timeline
