/**
 * Database schema for Event Intelligence data.
 *
 * These tables store the outputs from the agent pipeline so results
 * can be cached, compared, and used for future recommendations.
 *
 * This schema is designed for use with Mastra's LibSQL storage,
 * but the SQL is standard and can be adapted to PostgreSQL/SQLite.
 */

export const SCHEMA_SQL = `
-- Event intelligence runs (one per /full-event-engine or individual endpoint call)
CREATE TABLE IF NOT EXISTS intelligence_runs (
  id TEXT PRIMARY KEY,
  tenant_id TEXT,
  event_name TEXT NOT NULL,
  artist_name TEXT NOT NULL,
  venue_name TEXT NOT NULL,
  city TEXT NOT NULL,
  event_date TEXT NOT NULL,
  event_type TEXT NOT NULL,
  genre TEXT,
  capacity INTEGER,
  ticket_price_min REAL,
  ticket_price_max REAL,
  status TEXT NOT NULL DEFAULT 'pending',  -- pending, running, completed, failed
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  completed_at TEXT,
  processing_time_ms INTEGER,
  error TEXT
);

-- Research results
CREATE TABLE IF NOT EXISTS research_results (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES intelligence_runs(id),
  engagement_score REAL,
  city_demand TEXT,
  market_saturation TEXT,
  estimated_attendance INTEGER,
  sell_through_prediction REAL,
  confidence REAL,
  full_output TEXT NOT NULL,  -- Full JSON output from research agent
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Audience segments
CREATE TABLE IF NOT EXISTS audience_segments (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES intelligence_runs(id),
  segment_name TEXT NOT NULL,
  description TEXT,
  size_estimate TEXT,
  age_range TEXT,
  interests TEXT,           -- JSON array
  behaviors TEXT,           -- JSON array
  platforms TEXT,            -- JSON array
  messaging_angle TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Marketing strategies
CREATE TABLE IF NOT EXISTS marketing_strategies (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES intelligence_runs(id),
  campaign_name TEXT NOT NULL,
  total_budget REAL,
  expected_roas REAL,
  phases TEXT NOT NULL,       -- JSON array of campaign phases
  messaging TEXT NOT NULL,    -- JSON messaging strategy
  content_calendar TEXT,      -- JSON content calendar
  full_output TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Ad campaigns (generated by Media Buyer Agent)
CREATE TABLE IF NOT EXISTS ad_campaigns (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES intelligence_runs(id),
  campaign_name TEXT NOT NULL,
  objective TEXT NOT NULL,
  daily_budget REAL,
  total_budget REAL,
  funnel_stage TEXT,           -- cold, warm, hot
  targeting TEXT NOT NULL,     -- JSON targeting configuration
  ad_copy TEXT NOT NULL,       -- JSON ad copy variations
  scaling_logic TEXT,          -- JSON scaling rules
  expected_results TEXT,       -- JSON expected performance
  meta_campaign_id TEXT,       -- External Meta campaign ID (if published)
  status TEXT DEFAULT 'draft', -- draft, active, paused, completed
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Creative assets (generated by Creative Director Agent)
CREATE TABLE IF NOT EXISTS creative_assets (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES intelligence_runs(id),
  platform TEXT NOT NULL,       -- instagram, tiktok, facebook, banner, flyer
  content_type TEXT NOT NULL,   -- feed_post, story, reel, video, banner, flyer
  concept TEXT NOT NULL,
  image_prompt TEXT,
  caption TEXT,
  script TEXT,
  hashtags TEXT,                -- JSON array
  full_output TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Platform listings (generated by Distribution Agent)
CREATE TABLE IF NOT EXISTS platform_listings (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES intelligence_runs(id),
  platform TEXT NOT NULL,        -- aitickets, eventbrite, facebook_events, venue_cms
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT,
  tags TEXT,                     -- JSON array
  custom_fields TEXT,            -- JSON platform-specific fields
  seo_title TEXT,
  seo_description TEXT,
  seo_keywords TEXT,             -- JSON array
  ready_to_publish INTEGER DEFAULT 0,
  validation_issues TEXT,        -- JSON array
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Publishing logs
CREATE TABLE IF NOT EXISTS publishing_logs (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES intelligence_runs(id),
  listing_id TEXT REFERENCES platform_listings(id),
  platform TEXT NOT NULL,
  status TEXT NOT NULL,           -- success, failed, skipped
  platform_event_id TEXT,
  live_url TEXT,
  error TEXT,
  published_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Artist cache (reusable across events)
CREATE TABLE IF NOT EXISTS artists (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  genre TEXT,
  monthly_listeners INTEGER,
  instagram_followers INTEGER,
  tiktok_followers INTEGER,
  twitter_followers INTEGER,
  spotify_followers INTEGER,
  engagement_score REAL,
  similar_artists TEXT,           -- JSON array
  last_researched_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Venue cache
CREATE TABLE IF NOT EXISTS venues_intel (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  capacity INTEGER,
  typical_events TEXT,            -- JSON array
  area_demographics TEXT,
  last_researched_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(name, city)
);

-- Engagement scores history (for trend tracking)
CREATE TABLE IF NOT EXISTS engagement_history (
  id TEXT PRIMARY KEY,
  artist_id TEXT REFERENCES artists(id),
  score REAL NOT NULL,
  measured_at TEXT NOT NULL DEFAULT (datetime('now')),
  source TEXT                     -- web_search, social_api, manual
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_runs_tenant ON intelligence_runs(tenant_id);
CREATE INDEX IF NOT EXISTS idx_runs_artist ON intelligence_runs(artist_name);
CREATE INDEX IF NOT EXISTS idx_runs_city ON intelligence_runs(city);
CREATE INDEX IF NOT EXISTS idx_runs_status ON intelligence_runs(status);
CREATE INDEX IF NOT EXISTS idx_research_run ON research_results(run_id);
CREATE INDEX IF NOT EXISTS idx_segments_run ON audience_segments(run_id);
CREATE INDEX IF NOT EXISTS idx_strategies_run ON marketing_strategies(run_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_run ON ad_campaigns(run_id);
CREATE INDEX IF NOT EXISTS idx_creatives_run ON creative_assets(run_id);
CREATE INDEX IF NOT EXISTS idx_listings_run ON platform_listings(run_id);
CREATE INDEX IF NOT EXISTS idx_publishing_run ON publishing_logs(run_id);
CREATE INDEX IF NOT EXISTS idx_artists_name ON artists(name);
CREATE INDEX IF NOT EXISTS idx_venues_city ON venues_intel(city);
`;

export default SCHEMA_SQL;
