"""
Alerts API - View and manage in-app notifications

Provides endpoints for viewing alerts generated by the autonomous intelligence
system, marking them as read, and getting alert statistics.
"""

from fastapi import APIRouter, Depends, HTTPException, Request, Query
from sqlalchemy.orm import Session
from typing import List, Optional
from pydantic import BaseModel
from datetime import datetime

from app.database import get_db
from app.models import Alert, AlertSeverity
from app.rate_limit import limiter

router = APIRouter(prefix="/alerts", tags=["alerts"])


# Pydantic schemas
class AlertResponse(BaseModel):
    id: int
    title: str
    message: str
    severity: str
    event_id: Optional[int]
    alert_metadata: Optional[str]
    is_read: bool
    read_at: Optional[datetime]
    channels_sent: Optional[str]
    created_at: datetime

    class Config:
        from_attributes = True


class AlertStats(BaseModel):
    total: int
    unread: int
    by_severity: dict


@router.get("", response_model=List[AlertResponse])
@limiter.limit("60/minute")
async def list_alerts(
    request: Request,
    is_read: Optional[bool] = Query(None),
    severity: Optional[str] = Query(None),
    limit: int = Query(50, le=100),
    offset: int = Query(0),
    db: Session = Depends(get_db),
):
    """
    Get list of alerts with optional filtering.

    **Query Parameters:**
    - `is_read`: Filter by read status (true/false)
    - `severity`: Filter by severity (low/medium/high/critical)
    - `limit`: Max alerts to return (default 50, max 100)
    - `offset`: Pagination offset

    **Returns:** List of alerts ordered by creation time (newest first)
    """
    query = db.query(Alert)

    # Apply filters
    if is_read is not None:
        query = query.filter(Alert.is_read == is_read)

    if severity:
        try:
            severity_enum = AlertSeverity[severity.upper()]
            query = query.filter(Alert.severity == severity_enum)
        except KeyError:
            raise HTTPException(
                status_code=400,
                detail=f"Invalid severity: {severity}. Valid: low, medium, high, critical",
            )

    # Order by newest first
    query = query.order_by(Alert.created_at.desc())

    # Pagination
    alerts = query.offset(offset).limit(limit).all()

    return [
        AlertResponse(
            id=a.id,
            title=a.title,
            message=a.message,
            severity=a.severity.value if hasattr(a.severity, "value") else a.severity,
            event_id=a.event_id,
            alert_metadata=a.alert_metadata,
            is_read=a.is_read,
            read_at=a.read_at,
            channels_sent=a.channels_sent,
            created_at=a.created_at,
        )
        for a in alerts
    ]


@router.get("/stats", response_model=AlertStats)
@limiter.limit("60/minute")
async def get_alert_stats(
    request: Request,
    db: Session = Depends(get_db),
):
    """
    Get alert statistics.

    **Returns:**
    - Total alert count
    - Unread alert count
    - Alert counts by severity
    """
    total = db.query(Alert).count()
    unread = db.query(Alert).filter(Alert.is_read == False).count()

    # Count by severity
    by_severity = {}
    for severity in AlertSeverity:
        count = db.query(Alert).filter(Alert.severity == severity).count()
        by_severity[severity.value] = count

    return AlertStats(
        total=total,
        unread=unread,
        by_severity=by_severity,
    )


@router.get("/{alert_id}", response_model=AlertResponse)
@limiter.limit("60/minute")
async def get_alert(
    request: Request,
    alert_id: int,
    db: Session = Depends(get_db),
):
    """Get a specific alert by ID."""
    alert = db.query(Alert).filter(Alert.id == alert_id).first()

    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")

    return AlertResponse(
        id=alert.id,
        title=alert.title,
        message=alert.message,
        severity=alert.severity.value if hasattr(alert.severity, "value") else alert.severity,
        event_id=alert.event_id,
        alert_metadata=alert.alert_metadata,
        is_read=alert.is_read,
        read_at=alert.read_at,
        channels_sent=alert.channels_sent,
        created_at=alert.created_at,
    )


@router.patch("/{alert_id}/mark-read")
@limiter.limit("60/minute")
async def mark_alert_read(
    request: Request,
    alert_id: int,
    db: Session = Depends(get_db),
):
    """Mark an alert as read."""
    alert = db.query(Alert).filter(Alert.id == alert_id).first()

    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")

    if not alert.is_read:
        alert.is_read = True
        alert.read_at = datetime.utcnow()
        db.commit()

    return {"status": "marked_read", "alert_id": alert_id}


@router.patch("/{alert_id}/mark-unread")
@limiter.limit("60/minute")
async def mark_alert_unread(
    request: Request,
    alert_id: int,
    db: Session = Depends(get_db),
):
    """Mark an alert as unread."""
    alert = db.query(Alert).filter(Alert.id == alert_id).first()

    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")

    if alert.is_read:
        alert.is_read = False
        alert.read_at = None
        db.commit()

    return {"status": "marked_unread", "alert_id": alert_id}


@router.post("/mark-all-read")
@limiter.limit("10/minute")
async def mark_all_alerts_read(
    request: Request,
    db: Session = Depends(get_db),
):
    """Mark all unread alerts as read."""
    unread_alerts = db.query(Alert).filter(Alert.is_read == False).all()

    count = 0
    for alert in unread_alerts:
        alert.is_read = True
        alert.read_at = datetime.utcnow()
        count += 1

    db.commit()

    return {"status": "success", "marked_read": count}


@router.delete("/{alert_id}")
@limiter.limit("30/minute")
async def delete_alert(
    request: Request,
    alert_id: int,
    db: Session = Depends(get_db),
):
    """Delete an alert."""
    alert = db.query(Alert).filter(Alert.id == alert_id).first()

    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")

    db.delete(alert)
    db.commit()

    return {"status": "deleted", "alert_id": alert_id}
